version: '3'

services:

  dash:
    container_name: dash
    restart: always
    build: ./application
    ports:
      - "8000:8000"
    volumes:
      - ./application:/code
    command: python app.py
