version: '3'

services:

  dash:
    container_name: dash
    restart: always
    build: ./application
    ports:
      - "8000:8000"
    command: gunicorn app:server --bind 0.0.0.0:8000 --workers=4 --timeout 10
